"""
JARVIS Security Alert Manager
Version: 8.3

Central alert management layer between:
    Security Notifications
            ↓
    Security Alert Manager
            ↓
    JARVIS / UI / Voice Layer

Responsibilities:
- Receive security notifications/events.
- Convert events into managed security alerts.
- Assign alert severity and priority.
- Deduplicate repeated alerts.
- Track active, acknowledged and resolved alerts.
- Maintain alert history.
- Notify connected JARVIS/UI callbacks.
- Provide alert statistics.
- Never perform destructive security actions directly.
"""

from __future__ import annotations

import threading
import time

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional


class SecurityAlertManager:
    """
    V8.3 Security Alert Manager.

    Manages security alerts generated by the Security system
    and forwards important events to JARVIS or other listeners.
    """

    VERSION = "8.3"

    # =========================================================
    # ALERT STATES
    # =========================================================

    STATE_ACTIVE = "active"
    STATE_ACKNOWLEDGED = "acknowledged"
    STATE_RESOLVED = "resolved"
    STATE_DISMISSED = "dismissed"

    # =========================================================
    # SEVERITY
    # =========================================================

    SEVERITY_INFO = "info"
    SEVERITY_NOTICE = "notice"
    SEVERITY_WARNING = "warning"
    SEVERITY_HIGH = "high"
    SEVERITY_CRITICAL = "critical"

    # =========================================================
    # PRIORITY
    # =========================================================

    PRIORITY_LOW = 1
    PRIORITY_NORMAL = 2
    PRIORITY_HIGH = 3
    PRIORITY_URGENT = 4
    PRIORITY_CRITICAL = 5

    # =========================================================
    # ALERT TYPES
    # =========================================================

    ALERT_SYSTEM = "system"
    ALERT_SCAN = "scan"
    ALERT_THREAT = "threat"
    ALERT_NETWORK = "network"
    ALERT_FIREWALL = "firewall"
    ALERT_DNS = "dns"
    ALERT_STARTUP = "startup"
    ALERT_USB = "usb"
    ALERT_PROCESS = "process"
    ALERT_QUARANTINE = "quarantine"
    ALERT_REMEDIATION = "remediation"
    ALERT_RECOVERY = "recovery"
    ALERT_USER = "user"
    ALERT_ERROR = "error"
    ALERT_UNKNOWN = "unknown"

    # =========================================================
    # CONSTRUCTOR
    # =========================================================

    def __init__(
        self,
        notifications: Any = None,
        logger: Any = None,
        callback: Optional[
            Callable[[Dict[str, Any]], None]
        ] = None,
        max_history: int = 500,
        deduplication_window: float = 30.0,
    ) -> None:

        self.notifications = notifications

        self.logger = logger

        self.callback = callback

        self.max_history = max(
            1,
            int(max_history),
        )

        self.deduplication_window = max(
            0.0,
            float(deduplication_window),
        )

        self._lock = threading.RLock()

        self._alerts: Dict[
            str,
            Dict[str, Any],
        ] = {}

        self._history: List[
            Dict[str, Any]
        ] = []

        self._listeners: List[
            Callable[[Dict[str, Any]], None]
        ] = []

        self._counter = 0

        self._status = "idle"

        self._enabled = True

        self._stats = {
            "total_alerts": 0,
            "active_alerts": 0,
            "acknowledged_alerts": 0,
            "resolved_alerts": 0,
            "dismissed_alerts": 0,
            "critical_alerts": 0,
            "high_alerts": 0,
            "warning_alerts": 0,
            "notice_alerts": 0,
            "info_alerts": 0,
            "deduplicated_alerts": 0,
        }

        self._notification_callback_connected = False

    # =========================================================
    # ALERT CREATION
    # =========================================================

    def create_alert(
        self,
        title: str,
        message: str,
        severity: str = SEVERITY_INFO,
        alert_type: str = ALERT_UNKNOWN,
        source: str = "security",
        target: Any = None,
        threat_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
        priority: Optional[int] = None,
    ) -> Dict[str, Any]:

        with self._lock:

            if not self._enabled:

                return {
                    "success": False,
                    "created": False,
                    "message": (
                        "Менеджер тревог отключён."
                    ),
                }

            severity = self._normalize_severity(
                severity
            )

            alert_type = (
                alert_type
                or self.ALERT_UNKNOWN
            )

            if priority is None:

                priority = self._severity_to_priority(
                    severity
                )

            dedup_key = self._build_dedup_key(
                title=title,
                message=message,
                alert_type=alert_type,
                target=target,
                threat_id=threat_id,
            )

            existing = self._find_recent_duplicate(
                dedup_key
            )

            if existing is not None:

                existing["occurrences"] = (
                    int(
                        existing.get(
                            "occurrences",
                            1,
                        )
                    )
                    + 1
                )

                existing["last_seen"] = time.time()

                self._stats[
                    "deduplicated_alerts"
                ] += 1

                self._log(
                    "info",
                    (
                        "Duplicate security alert "
                        f"deduplicated: "
                        f"{existing.get('id')}"
                    ),
                )

                self._emit(
                    existing,
                    event="updated",
                )

                return {
                    "success": True,
                    "created": False,
                    "deduplicated": True,
                    "alert": dict(existing),
                }

            alert_id = self._generate_alert_id()

            now = time.time()

            alert = {
                "id": alert_id,
                "title": str(title or "Security Alert"),
                "message": str(message or ""),
                "severity": severity,
                "priority": int(priority),
                "type": alert_type,
                "source": source,
                "target": target,
                "threat_id": threat_id,
                "metadata": dict(
                    metadata or {}
                ),
                "state": self.STATE_ACTIVE,
                "created_at": now,
                "updated_at": now,
                "last_seen": now,
                "acknowledged_at": None,
                "resolved_at": None,
                "dismissed_at": None,
                "occurrences": 1,
                "dedup_key": dedup_key,
            }

            self._alerts[alert_id] = alert

            self._history.append(
                dict(alert)
            )

            self._trim_history()

            self._stats[
                "total_alerts"
            ] += 1

            self._stats[
                f"{severity}_alerts"
            ] += 1

            self._recalculate_state_stats()

            self._status = "alert_created"

            self._log(
                "warning"
                if severity in {
                    self.SEVERITY_WARNING,
                    self.SEVERITY_HIGH,

            self.SEVERITY_CRITICAL,
                }
                else "info",
                (
                    "Security alert created: "
                    f"{alert_id} "
                    f"[{severity}] "
                    f"{title}"
                ),
            )

            self._emit(
                alert,
                event="created",
            )

            return {
                "success": True,
                "created": True,
                "deduplicated": False,
                "alert": dict(alert),
            }

    # =========================================================
    # NOTIFICATION HANDLING
    # =========================================================

    def handle_notification(
        self,
        notification: Any,
    ) -> Dict[str, Any]:

        if notification is None:

            return {
                "success": False,
                "created": False,
                "message": (
                    "Пустое уведомление."
                ),
            }

        if isinstance(
            notification,
            dict,
        ):

            data = dict(notification)

        else:

            try:

                data = {
                    "message": str(
                        notification
                    )
                }

            except Exception:

                data = {
                    "message": (
                        "Неизвестное уведомление."
                    )
                }

        title = (
            data.get("title")
            or data.get("name")
            or data.get("type")
            or "Security Alert"
        )

        message = (
            data.get("message")
            or data.get("description")
            or data.get("text")
            or ""
        )

        severity = self._extract_severity(
            data
        )

        alert_type = self._notification_to_alert_type(
            data
        )

        source = (
            data.get(
                "source",
                "security_notifications",
            )
        )

        target = data.get(
            "target"
        )

        threat_id = (
            data.get("threat_id")
            or data.get("threatId")
            or data.get("id")
            if alert_type == self.ALERT_THREAT
            else None
        )

        metadata = dict(data)

        return self.create_alert(
            title=str(title),
            message=str(message),
            severity=severity,
            alert_type=alert_type,
            source=str(source),
            target=target,
            threat_id=threat_id,
            metadata=metadata,
        )

    # =========================================================
    # CONVENIENCE METHODS
    # =========================================================

    def info(
        self,
        title: str,
        message: str,
        **kwargs: Any,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=self.SEVERITY_INFO,
            **kwargs,
        )

    def notice(
        self,
        title: str,
        message: str,
        **kwargs: Any,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=self.SEVERITY_NOTICE,
            **kwargs,
        )

    def warning(
        self,
        title: str,
        message: str,
        **kwargs: Any,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=self.SEVERITY_WARNING,
            **kwargs,
        )

    def high(
        self,
        title: str,
        message: str,
        **kwargs: Any,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=self.SEVERITY_HIGH,
            **kwargs,
        )

    def critical(

        self,
        title: str,
        message: str,
        **kwargs: Any,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=self.SEVERITY_CRITICAL,
            **kwargs,
        )

    # =========================================================
    # THREAT ALERTS
    # =========================================================

    def threat_detected(
        self,
        title: str,
        message: str,
        threat_id: Optional[str] = None,
        target: Any = None,
        severity: str = SEVERITY_HIGH,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=severity,
            alert_type=self.ALERT_THREAT,
            source="security",
            target=target,
            threat_id=threat_id,
            metadata=metadata,
        )

    def threat_blocked(
        self,
        title: str,
        message: str,
        threat_id: Optional[str] = None,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=self.SEVERITY_HIGH,
            alert_type=self.ALERT_THREAT,
            source="security",
            target=target,
            threat_id=threat_id,
            metadata=metadata,
        )

    def threat_quarantined(
        self,
        title: str,
        message: str,
        threat_id: Optional[str] = None,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=self.SEVERITY_NOTICE,
            alert_type=self.ALERT_QUARANTINE,
            source="security",
            target=target,
            threat_id=threat_id,
            metadata=metadata,
        )

    # =========================================================
    # SCAN ALERTS
    # =========================================================

    def scan_started(
        self,
        scan_type: str,
        target: Any = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title="Security Scan Started",
            message=(
                f"Запущена проверка безопасности: "
                f"{scan_type}."
            ),
            severity=self.SEVERITY_INFO,
            alert_type=self.ALERT_SCAN,
            source="security",
            target=target,
            metadata={
                "scan_type": scan_type,
                "event": "started",
            },
        )

    def scan_completed(
        self,
        scan_type: str,
        success: bool = True,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        severity = (
            self.SEVERITY_INFO
            if success
            else self.SEVERITY_WARNING
        )

        return self.create_alert(
            title="Security Scan Completed",
            message=(
                f"Проверка безопасности "
                f"{scan_type} завершена."
            ),
            severity=severity,
            alert_type=self.ALERT_SCAN,
            source="security",
            target=target,
            metadata={
                "scan_type": scan_type,
                "event": "completed",
                "success": success,
                **dict(metadata or {}),
            },
        )

    # =========================================================
    # NETWORK / SYSTEM ALERTS
    # =========================================================

    def network_alert(
        self,
        title: str,
        message: str,
        severity: str = SEVERITY_WARNING,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,

) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=severity,
            alert_type=self.ALERT_NETWORK,
            source="network",
            target=target,
            metadata=metadata,
        )

    def firewall_alert(
        self,
        title: str,
        message: str,
        severity: str = SEVERITY_WARNING,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=severity,
            alert_type=self.ALERT_FIREWALL,
            source="firewall",
            target=target,
            metadata=metadata,
        )

    def dns_alert(
        self,
        title: str,
        message: str,
        severity: str = SEVERITY_WARNING,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=severity,
            alert_type=self.ALERT_DNS,
            source="dns",
            target=target,
            metadata=metadata,
        )

    def startup_alert(
        self,
        title: str,
        message: str,
        severity: str = SEVERITY_WARNING,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=severity,
            alert_type=self.ALERT_STARTUP,
            source="startup",
            target=target,
            metadata=metadata,
        )

    def usb_alert(
        self,
        title: str,
        message: str,
        severity: str = SEVERITY_WARNING,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=severity,
            alert_type=self.ALERT_USB,
            source="usb",
            target=target,
            metadata=metadata,
        )

    def process_alert(
        self,
        title: str,
        message: str,
        severity: str = SEVERITY_WARNING,
        target: Any = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:

        return self.create_alert(
            title=title,
            message=message,
            severity=severity,
            alert_type=self.ALERT_PROCESS,
            source="process",
            target=target,
            metadata=metadata,
        )

    # =========================================================
    # ALERT STATE MANAGEMENT
    # =========================================================

    def acknowledge(
        self,
        alert_id: str,
    ) -> Dict[str, Any]:

        with self._lock:

            alert = self._alerts.get(
                str(alert_id)
            )

            if alert is None:

                return {
                    "success": False,
                    "message": (
                        "Тревога не найдена."
                    ),
                }

            if alert["state"] in {
                self.STATE_RESOLVED,
                self.STATE_DISMISSED,
            }:

                return {
                    "success": False,
                    "message": (
                        "Тревога уже закрыта."
                    ),
                    "alert": dict(alert),
                }

            now = time.time()

            alert["state"] = (
                self.STATE_ACKNOWLEDGED
            )

            alert["acknowledged_at"] = now
            alert["updated_at"] = now

            self._recalculate_state_stats()

            self._log(
                "info",
                (
                    "Security alert acknowledged: "

f"{alert_id}"
                ),
            )

            self._emit(
                alert,
                event="acknowledged",
            )

            return {
                "success": True,
                "alert": dict(alert),
            }

    def resolve(
        self,
        alert_id: str,
        resolution: Optional[str] = None,
    ) -> Dict[str, Any]:

        with self._lock:

            alert = self._alerts.get(
                str(alert_id)
            )

            if alert is None:

                return {
                    "success": False,
                    "message": (
                        "Тревога не найдена."
                    ),
                }

            now = time.time()

            alert["state"] = (
                self.STATE_RESOLVED
            )

            alert["resolved_at"] = now
            alert["updated_at"] = now

            if resolution:

                alert.setdefault(
                    "metadata",
                    {},
                )["resolution"] = (
                    resolution
                )

            self._recalculate_state_stats()

            self._log(
                "info",
                (
                    "Security alert resolved: "
                    f"{alert_id}"
                ),
            )

            self._emit(
                alert,
                event="resolved",
            )

            return {
                "success": True,
                "alert": dict(alert),
            }

    def dismiss(
        self,
        alert_id: str,
        reason: Optional[str] = None,
    ) -> Dict[str, Any]:

        with self._lock:

            alert = self._alerts.get(
                str(alert_id)
            )

            if alert is None:

                return {
                    "success": False,
                    "message": (
                        "Тревога не найдена."
                    ),
                }

            now = time.time()

            alert["state"] = (
                self.STATE_DISMISSED
            )

            alert["dismissed_at"] = now
            alert["updated_at"] = now

            if reason:

                alert.setdefault(
                    "metadata",
                    {},
                )["dismiss_reason"] = (
                    reason
                )

            self._recalculate_state_stats()

            self._log(
                "info",
                (
                    "Security alert dismissed: "
                    f"{alert_id}"
                ),
            )

            self._emit(
                alert,
                event="dismissed",
            )

            return {
                "success": True,
                "alert": dict(alert),
            }

    # =========================================================
    # GETTERS
    # =========================================================

    def get_alert(
        self,
        alert_id: str,
    ) -> Optional[Dict[str, Any]]:

        with self._lock:

            alert = self._alerts.get(
                str(alert_id)
            )

            if alert is None:

                return None

            return dict(alert)

    def get_active_alerts(
        self,
    ) -> List[Dict[str, Any]]:

        with self._lock:

            return [
                dict(alert)
                for alert in self._alerts.values()
                if alert["state"]
                in {
                    self.STATE_ACTIVE,
                    self.STATE_ACKNOWLEDGED,
                }
            ]

    def get_unacknowledged_alerts(
        self,
    ) -> List[Dict[str, Any]]:

        with self._lock:

            return [
                dict(alert)
                for alert in self._alerts.values()
                if alert["state"]
                == self.STATE_ACTIVE
            ]

    def get_critical_alerts(
        self,
    ) -> List[Dict[str, Any]]:

        with self._lock:

            return [
                dict(alert)
                for alert in self._alerts.values()
                if alert["severity"]
                == self.SEVERITY_CRITICAL
                and alert["state"]
                in {
                    self.STATE_ACTIVE,
                    self.STATE_ACKNOWLEDGED,
                }
            ]

    def get_alerts(
        self,
        state: Optional[str] = None,
        severity: Optional[str] = None,
        alert_type: Optional[str] = None,
        limit: Optional[int] = None,
    ) -> List[Dict[str, Any]]:

        with self._lock:

            alerts = list(
                self._alerts.values()
            )

            if state is not None:

                alerts = [
                    alert
                    for alert in alerts
                    if alert["state"]
                    == state
                ]

            if severity is not None:

                severity = (
                    self._normalize_severity(
                        severity
                    )
                )

                alerts = [
                    alert
                    for alert in alerts
                    if alert["severity"]
                    == severity
                ]

            if alert_type is not None:

                alerts = [
                    alert
                    for alert in alerts
                    if alert["type"]
                    == alert_type
                ]

            alerts.sort(
                key=lambda item: (
                    int(
                        item.get(
                            "priority",
                            0,
                        )
                    ),
                    float(
                        item.get(
                            "created_at",
                            0,
                        )
                    ),
                ),
                reverse=True,
            )

            if limit is not None:

                limit = max(
                    0,
                    int(limit),
                )

                alerts = alerts[:limit]

            return [
                dict(alert)
                for alert in alerts
            ]

    def get_history(
        self,
        limit: Optional[int] = None,
    ) -> List[Dict[str, Any]]:

        with self._lock:

            history = list(
                self._history
            )

            history.reverse()

            if limit is not None:

                history = history[
                    : max(
                        0,
                        int(limit),
                    )
                ]

            return [
                dict(item)
                for item in history
            ]

    # =========================================================
    # STATISTICS
    # =========================================================

    def get_stats(
        self,
    ) -> Dict[str, Any]:

        with self._lock:

            self._recalculate_state_stats()

            return dict(
                self._stats
            )

    def get_unread_count(
        self,
    ) -> int:

        with self._lock:

            return len(
                [
                    alert
                    for alert in self._alerts.values()
                    if alert["state"]
                    == self.STATE_ACTIVE
                ]
            )

    def get_critical_count(
        self,
    ) -> int:

        with self._lock:

            return len(
                self.get_critical_alerts()
            )

    # =========================================================
    # LISTENERS
    # =========================================================

    def subscribe(
        self,
        callback: Callable[
            [Dict[str, Any]],
            None,
        ],
    ) -> bool:

        if not callable(callback):

            return False

        with self._lock:

            if callback not in self._listeners:

                self._listeners.append(
                    callback
                )

            return True

    def unsubscribe(
        self,
        callback: Callable[
            [Dict[str, Any]],
            None,
        ],
    ) -> bool:

        with self._lock:

            if callback in self._listeners:

                self._listeners.remove(
                    callback
                )

                return True

            return False

    def set_callback(
        self,
        callback: Optional[
            Callable[[Dict[str, Any]], None]
        ],
    ) -> None:

        with self._lock:

            self.callback = callback

    # =========================================================
    # NOTIFICATION CONNECTION
    # =========================================================

    def connect_notifications(
        self,
    ) -> Dict[str, Any]:

        with self._lock:

            if self.notifications is None:

                return {
                    "success": False,
                    "connected": False,
                    "message": (
                        "Security Notifications "
                        "не подключены."
                    ),
                }

            if self._notification_callback_connected:

                return {
                    "success": True,
                    "connected": True,
                    "message": (
                        "Security Notifications "
                        "уже подключены."
                    ),
                }

            try:

                if hasattr(
                    self.notifications,
                    "subscribe",
                ):

                    self.notifications.subscribe(
                        self._notification_handler
                    )

                    self._notification_callback_connected = True

                    self._log(
                        "info",
                        (
                            "Security Notifications "
                            "connected to Alert Manager."
                        ),
                    )

                    return {
                        "success": True,
                        "connected": True,
                    }

                return {
                    "success": False,
                    "connected": False,
                    "message": (
                        "Notifications API "
                        "не поддерживает subscribe."
                    ),
                }

            except Exception as exc:

                self._log(
                    "error",
                    (
                        "Notification connection "
                        f"error: {exc}"
                    ),
                )

                return {
                    "success": False,
                    "connected": False,
                    "error": str(exc),
                }

    def disconnect_notifications(
        self,
    ) -> Dict[str, Any]:

        with self._lock:

            if self.notifications is None:

                return {
                    "success": False,
                    "connected": False,
                }

            try:

                if hasattr(
                    self.notifications,
                    "unsubscribe",
                ):

                    self.notifications.unsubscribe(
                        self._notification_handler
                    )

                self._notification_callback_connected = False

                return {
                    "success": True,
                    "connected": False,
                }

            except Exception as exc:

                self._log(
                    "error",
                    (
                        "Notification disconnect "
                        f"error: {exc}"
                    ),
                )

                return {

"success": False,
                    "connected": (
                        self._notification_callback_connected
                    ),
                    "error": str(exc),
                }

    def _notification_handler(
        self,
        notification: Any,
    ) -> None:

        try:

            self.handle_notification(
                notification
            )

        except Exception as exc:

            self._log(
                "error",
                (
                    "Notification handler error: "
                    f"{exc}"
                ),
            )

    # =========================================================
    # ENABLE / DISABLE
    # =========================================================

    def enable(self) -> Dict[str, Any]:

        with self._lock:

            self._enabled = True
            self._status = "enabled"

            return {
                "success": True,
                "enabled": True,
            }

    def disable(self) -> Dict[str, Any]:

        with self._lock:

            self._enabled = False
            self._status = "disabled"

            return {
                "success": True,
                "enabled": False,
            }

    def is_enabled(
        self,
    ) -> bool:

        with self._lock:

            return self._enabled

    # =========================================================
    # CLEARING
    # =========================================================

    def clear_resolved(
        self,
    ) -> int:

        with self._lock:

            resolved_ids = [
                alert_id
                for alert_id, alert in self._alerts.items()
                if alert["state"]
                in {
                    self.STATE_RESOLVED,
                    self.STATE_DISMISSED,
                }
            ]

            for alert_id in resolved_ids:

                self._alerts.pop(
                    alert_id,
                    None,
                )

            self._recalculate_state_stats()

            return len(
                resolved_ids
            )

    def clear_all(
        self,
    ) -> Dict[str, Any]:

        with self._lock:

            count = len(
                self._alerts
            )

            self._alerts.clear()

            self._recalculate_state_stats()

            self._status = "cleared"

            return {
                "success": True,
                "cleared": count,
            }

    # =========================================================
    # HEALTH / STATUS
    # =========================================================

    def get_status(
        self,
    ) -> Dict[str, Any]:

        with self._lock:

            self._recalculate_state_stats()

            return {
                "version": self.VERSION,
                "status": self._status,
                "enabled": self._enabled,
                "notifications_connected": (
                    self._notification_callback_connected
                ),
                "active_alerts": (
                    self._stats[
                        "active_alerts"
                    ]
                ),
                "unread_alerts": (
                    self.get_unread_count()
                ),
                "critical_alerts": (
                    self._stats[
                        "critical_alerts"
                    ]
                ),
                "listeners": len(
                    self._listeners
                ),
                "history_size": len(
                    self._history
                ),
            }

    def health_check(
        self,
    ) -> Dict[str, Any]:

        with self._lock:

            healthy = True
            problems: List[str] = []

            if not self._enabled:

                healthy = False

                problems.append(
                    "Alert Manager отключён."
                )

            if self.max_history < 1:

                healthy = False

                problems.append(
                    "Некорректный размер истории."
                )

            if self.deduplication_window < 0:

                healthy = False

                problems.append(
                    "Некорректное окно дедупликации."
                )

            return {
                "healthy": healthy,
                "version": self.VERSION,
                "problems": problems,
            }

    # =========================================================
    # RESET
    # =========================================================

    def reset(
        self,
    ) -> Dict[str, Any]:

        with self._lock:

            self._alerts.clear()

            self._history.clear()

            self._counter = 0

            for key in self._stats:

                self._stats[key] = 0

            self._status = "reset"

            return {
                "success": True,
                "message": (
                    "Alert Manager сброшен."
                ),
            }

    # =========================================================
    # INTERNAL HELPERS
    # =========================================================

    def _generate_alert_id(
        self,
    ) -> str:

        self._counter += 1

        return (
            f"ALERT-"
            f"{int(time.time())}-"
            f"{self._counter:06d}"
        )

    def _normalize_severity(
        self,
        severity: Any,
    ) -> str:

        value = str(
            severity or self.SEVERITY_INFO
        ).lower().strip()

        aliases = {
            "low": self.SEVERITY_INFO,
            "normal": self.SEVERITY_NOTICE,
            "medium": self.SEVERITY_WARNING,
            "warn": self.SEVERITY_WARNING,
            "danger": self.SEVERITY_HIGH,
            "urgent": self.SEVERITY_HIGH,
            "severe": self.SEVERITY_HIGH,
            "fatal": self.SEVERITY_CRITICAL,
        }

        value = aliases.get(
            value,
            value,
        )

        if value not in {
            self.SEVERITY_INFO,
            self.SEVERITY_NOTICE,
            self.SEVERITY_WARNING,
            self.SEVERITY_HIGH,
            self.SEVERITY_CRITICAL,
        }:

            value = self.SEVERITY_INFO

        return value

    def _severity_to_priority(
        self,
        severity: str,
    ) -> int:

        mapping = {
            self.SEVERITY_INFO:
                self.PRIORITY_LOW,

            self.SEVERITY_NOTICE:
                self.PRIORITY_NORMAL,

            self.SEVERITY_WARNING:
                self.PRIORITY_HIGH,

            self.SEVERITY_HIGH:
                self.PRIORITY_URGENT,

            self.SEVERITY_CRITICAL:
                self.PRIORITY_CRITICAL,
        }

        return mapping.get(
            severity,
            self.PRIORITY_LOW,
        )

    def _extract_severity(
        self,
        data: Dict[str, Any],
    ) -> str:

        severity = (
            data.get("severity")
            or data.get("level")
            or data.get("priority")
            or self.SEVERITY_INFO
        )

        if isinstance(
            severity,
            int,
        ):

            if severity >= 5:

                return self.SEVERITY_CRITICAL

            if severity >= 4:

                return self.SEVERITY_HIGH

            if severity >= 3:

                return self.SEVERITY_WARNING

            if severity >= 2:

                return self.SEVERITY_NOTICE

            return self.SEVERITY_INFO

        return self._normalize_severity(
            severity
        )

    def _notification_to_alert_type(
        self,
        data: Dict[str, Any],
    ) -> str:

        raw_type = str(
            data.get(
                "type",
                "",
            )
        ).lower()

        mapping = {
            "threat_detected":
                self.ALERT_THREAT,

            "threat_blocked":
                self.ALERT_THREAT,

            "threat_quarantined":
                self.ALERT_QUARANTINE,

            "scan_started":
                self.ALERT_SCAN,

            "scan_completed":
                self.ALERT_SCAN,

            "network":
                self.ALERT_NETWORK,

            "firewall":
                self.ALERT_FIREWALL,

            "dns":
                self.ALERT_DNS,

            "startup":
                self.ALERT_STARTUP,

            "usb":
                self.ALERT_USB,

            "process":
                self.ALERT_PROCESS,

            "recovery":
                self.ALERT_RECOVERY,

            "error":
                self.ALERT_ERROR,

            "system":
                self.ALERT_SYSTEM,

            "user_action":
                self.ALERT_USER,
        }

        return mapping.get(
            raw_type,
            self.ALERT_UNKNOWN,
        )

    def _build_dedup_key(
        self,
        title: str,
        message: str,
        alert_type: str,
        target: Any,
        threat_id: Optional[str],
    ) -> str:

        target_repr = self._safe_repr(
            target
        )

        return "|".join(
            [
                str(alert_type),
                str(title).strip().lower(),
                str(message).strip().lower(),
                target_repr,
                str(threat_id or ""),
            ]
        )

    def _find_recent_duplicate(
        self,
        dedup_key: str,
    ) -> Optional[Dict[str, Any]]:

        if self.deduplication_window <= 0:

            return None

        now = time.time()

        for alert in reversed(
            list(self._alerts.values())
        ):

            if alert.get(
                "dedup_key"
            ) != dedup_key:

                continue

            last_seen = float(
                alert.get(
                    "last_seen",
                    0,
                )
            )

            if (
                now - last_seen
                <= self.deduplication_window
            ):

                if alert.get(
                    "state"
                ) in {
                    self.STATE_ACTIVE,
                    self.STATE_ACKNOWLEDGED,
                }:

                    return alert

            else:

                break

        return None

    def _recalculate_state_stats(
        self,
    ) -> None:

        self._stats[
            "active_alerts"
        ] = 0

        self._stats[
            "acknowledged_alerts"
        ] = 0

        self._stats[
            "resolved_alerts"
        ] = 0

        self._stats[
            "dismissed_alerts"
        ] = 0

        for alert in self._alerts.values():

            state = alert.get(
                "state"
            )

            if state == self.STATE_ACTIVE:

                self._stats[
                    "active_alerts"
                ] += 1

            elif state == self.STATE_ACKNOWLEDGED:

                self._stats[
                    "acknowledged_alerts"
                ] += 1

            elif state == self.STATE_RESOLVED:

                self._stats[
                    "resolved_alerts"
                ] += 1

            elif state == self.STATE_DISMISSED:

                self._stats[
                    "dismissed_alerts"
                ] += 1

    def _trim_history(
        self,
    ) -> None:

        if len(
            self._history
        ) <= self.max_history:

            return

        overflow = (
            len(self._history)
            - self.max_history
        )

        del self._history[
            :overflow
        ]

    def _safe_repr(
        self,
        value: Any,
    ) -> str:

        try:

            return repr(
                value
            )

        except Exception:

            return "<unrepr>"

    def _emit(
        self,
        alert: Dict[str, Any],
        event: str,
    ) -> None:

        payload = {
            "event": event,
            "alert": dict(alert),
            "timestamp": time.time(),
            "manager_version": self.VERSION,
        }

        callbacks = list(
            self._listeners
        )

        if self.callback is not None:

            callbacks.append(
                self.callback
            )

        for callback in callbacks:

            try:

                callback(
                    dict(payload)
                )

            except Exception as exc:

                self._log(
                    "error",
                    (
                        "Alert callback error: "
                        f"{exc}"
                    ),
                )

    def _log(
        self,
        level: str,
        message: str,
    ) -> None:

        if self.logger is None:

            return

        try:

            if hasattr(
                self.logger,
                "log",
            ):

                self.logger.log(
                    level,
                    message,
                )

                return

            method = getattr(
                self.logger,
                level,
                None,
            )

            if callable(method):

                method(
                    message
                )

        except Exception:
            pass

    # =========================================================
    # REPRESENTATION
    # =========================================================

    def __repr__(
        self,
    ) -> str:

        return (
            f"<SecurityAlertManager "
            f"version={self.VERSION} "
            f"enabled={self._enabled} "
            f"alerts={len(self._alerts)}>"
        )


# =============================================================
# SINGLETON
# =============================================================

_security_alert_manager: Optional[
    SecurityAlertManager
] = None

_security_alert_manager_lock = threading.Lock()


def get_security_alert_manager(
    notifications: Any = None,
    logger: Any = None,
    callback: Optional[
        Callable[[Dict[str, Any]], None]
    ] = None,
) -> SecurityAlertManager:

    global _security_alert_manager

    with _security_alert_manager_lock:

        if _security_alert_manager is None:

            _security_alert_manager = (
                SecurityAlertManager(
                    notifications=notifications,
                    logger=logger,
                    callback=callback,
                )
            )

        else:

            if notifications is not None:

                _security_alert_manager.notifications = (
                    notifications
                )

            if logger is not None:

                _security_alert_manager.logger = (
                    logger
                )

            if callback is not None:

                _security_alert_manager.set_callback(
                    callback
                )

        return _security_alert_manager